// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1) {
  return window['go']['backend']['PeerStorage']['AddPeer'](arg1);
}

export function GetAllPeers() {
  return window['go']['backend']['PeerStorage']['GetAllPeers']();
}

export function GetPeer(arg1) {
  return window['go']['backend']['PeerStorage']['GetPeer'](arg1);
}

export function RemovePeer(arg1) {
  return window['go']['backend']['PeerStorage']['RemovePeer'](arg1);
}

export function UpdatePeer(arg1, arg2) {
  return window['go']['backend']['PeerStorage']['UpdatePeer'](arg1, arg2);
}
